/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  kotlin("jvm") version "2.0.0" apply false
}

group = "systems.terranatal.nanoerp"
version = "0.1.0-SNAPSHOT"
